on:
  push:
    branches:
      - main
jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Deploying to prod
        uses: appleboy/ssh-action@v1.0.0
        if: github.ref == 'refs/heads/main'
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
           export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/apps/securelog-llm-example
            git pull origin main
            yarn install
            yarn build
            cp -r dist/* /var/www/llm
            systemctl reload nginx